# active spring boot profile
spring:
   profiles:
      active: dev

---
# common - spring configuration
spring:

   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   jpa:
    hibernate:
      ddl-auto: update # 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
---

# dev profile - spring boot configuration

spring:
   config:
      activate:
         on-profile: dev
      
   # datasource
   datasource:
      username: root
      password: 1111
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testDB?characterEncoding=utf8

